export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "on-tertiary-fixed-variant": "#93000b",
        "surface-container-low": "#eff4ff",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#b1c7f0",
        "surface-variant": "#d3e4fe",
        "on-primary": "#ffffff",
        "on-surface": "#0b1c30",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#ff4840",
        "on-primary-container": "#778db2",
        "on-secondary-fixed": "#001551",
        "outline": "#74777f",
        "tertiary": "#2b0001",
        "tertiary-container": "#530003",
        "primary-container": "#0b2545",
        "on-tertiary-fixed": "#410002",
        "surface-container-high": "#dce9ff",
        "on-error": "#ffffff",
        "inverse-primary": "#b1c7f0",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed-variant": "#0039b5",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb4ab",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "surface-tint": "#495f82",
        "primary": "#001026",
        "surface-container": "#e5eeff",
        "secondary-fixed-dim": "#b7c4ff",
        "error": "#ba1a1a",
        "secondary-container": "#4069f2",
        "inverse-surface": "#213145",
        "on-primary-fixed": "#001c3b",
        "outline-variant": "#c4c6cf",
        "primary-fixed": "#d5e3ff",
        "on-primary-fixed-variant": "#314769",
        "error-container": "#ffdad6",
        "secondary-fixed": "#dce1ff",
        "tertiary-fixed": "#ffdad6",
        "secondary": "#1d4ed8",
        "on-secondary-container": "#fffbff",
        "on-surface-variant": "#44474e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin": "3rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "display-lg": ["Montserrat"],
        "display-lg-mobile": ["Montserrat"],
        "label-tactical": ["Montserrat"],
        "headline-sm": ["Montserrat"],
        "body-lg": ["Inter"],
        "headline-lg": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "label-md": ["Inter"],
        "headline-xl-mobile": ["Montserrat"],
        "label-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Montserrat"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "display-lg": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "display-lg-mobile": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "800"}],
        "label-tactical": ["11px", {"lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "700"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600"}],
        "headline-xl-mobile": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.015em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
