/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GuardingPatrolRouteImport } from './routes/guarding-patrol'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as TechCctvRouteImport } from './routes/tech-cctv'
import { Route as AboutAffiliationsRouteImport } from './routes/about/affiliations'
import { Route as AboutCorporateObjectivesRouteImport } from './routes/about/corporate-objectives'
import { Route as AboutOurBackgroundRouteImport } from './routes/about/our-background'
import { Route as AboutOurCoreValuesRouteImport } from './routes/about/our-core-values'
import { Route as AboutOurManagementRouteImport } from './routes/about/our-management'
import { Route as AboutOurMissionRouteImport } from './routes/about/our-mission'
import { Route as AboutOurVisionRouteImport } from './routes/about/our-vision'
import { Route as AboutTestimonialsRouteImport } from './routes/about/testimonials'
import { Route as ExploreBlogRouteImport } from './routes/explore/blog'
import { Route as ExploreCareersRouteImport } from './routes/explore/careers'
import { Route as ExploreGuardsRecruitmentRouteImport } from './routes/explore/guards-recruitment'
import { Route as ServicesAccessControlRouteImport } from './routes/services/access-control'
import { Route as ServicesCashInTransitRouteImport } from './routes/services/cash-in-transit'
import { Route as ServicesEscortServicesRouteImport } from './routes/services/escort-services'
import { Route as ServicesMaritimeSecurityRouteImport } from './routes/services/maritime-security'
import { Route as ServicesPersonalProtectionRouteImport } from './routes/services/personal-protection'
import { Route as ServicesReceptionProtocolRouteImport } from './routes/services/reception-protocol'
import { Route as ServicesSecurityEquipmentRouteImport } from './routes/services/security-equipment'
import { Route as ServicesSpecialInvestigationRouteImport } from './routes/services/special-investigation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardingPatrolRoute = GuardingPatrolRouteImport.update({
  id: '/guarding-patrol',
  path: '/guarding-patrol',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const TechCctvRoute = TechCctvRouteImport.update({
  id: '/tech-cctv',
  path: '/tech-cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAffiliationsRoute = AboutAffiliationsRouteImport.update({
  id: '/about/affiliations',
  path: '/about/affiliations',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCorporateObjectivesRoute =
  AboutCorporateObjectivesRouteImport.update({
    id: '/about/corporate-objectives',
    path: '/about/corporate-objectives',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutOurBackgroundRoute = AboutOurBackgroundRouteImport.update({
  id: '/about/our-background',
  path: '/about/our-background',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurCoreValuesRoute = AboutOurCoreValuesRouteImport.update({
  id: '/about/our-core-values',
  path: '/about/our-core-values',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurManagementRoute = AboutOurManagementRouteImport.update({
  id: '/about/our-management',
  path: '/about/our-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurMissionRoute = AboutOurMissionRouteImport.update({
  id: '/about/our-mission',
  path: '/about/our-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurVisionRoute = AboutOurVisionRouteImport.update({
  id: '/about/our-vision',
  path: '/about/our-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTestimonialsRoute = AboutTestimonialsRouteImport.update({
  id: '/about/testimonials',
  path: '/about/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreBlogRoute = ExploreBlogRouteImport.update({
  id: '/explore/blog',
  path: '/explore/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCareersRoute = ExploreCareersRouteImport.update({
  id: '/explore/careers',
  path: '/explore/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreGuardsRecruitmentRoute =
  ExploreGuardsRecruitmentRouteImport.update({
    id: '/explore/guards-recruitment',
    path: '/explore/guards-recruitment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAccessControlRoute = ServicesAccessControlRouteImport.update({
  id: '/services/access-control',
  path: '/services/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCashInTransitRoute = ServicesCashInTransitRouteImport.update({
  id: '/services/cash-in-transit',
  path: '/services/cash-in-transit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEscortServicesRoute = ServicesEscortServicesRouteImport.update({
  id: '/services/escort-services',
  path: '/services/escort-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaritimeSecurityRoute =
  ServicesMaritimeSecurityRouteImport.update({
    id: '/services/maritime-security',
    path: '/services/maritime-security',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPersonalProtectionRoute =
  ServicesPersonalProtectionRouteImport.update({
    id: '/services/personal-protection',
    path: '/services/personal-protection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesReceptionProtocolRoute =
  ServicesReceptionProtocolRouteImport.update({
    id: '/services/reception-protocol',
    path: '/services/reception-protocol',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSecurityEquipmentRoute =
  ServicesSecurityEquipmentRouteImport.update({
    id: '/services/security-equipment',
    path: '/services/security-equipment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSpecialInvestigationRoute =
  ServicesSpecialInvestigationRouteImport.update({
    id: '/services/special-investigation',
    path: '/services/special-investigation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/guarding-patrol': typeof GuardingPatrolRoute
  '/sectors': typeof SectorsRoute
  '/tech-cctv': typeof TechCctvRoute
  '/about/affiliations': typeof AboutAffiliationsRoute
  '/about/corporate-objectives': typeof AboutCorporateObjectivesRoute
  '/about/our-background': typeof AboutOurBackgroundRoute
  '/about/our-core-values': typeof AboutOurCoreValuesRoute
  '/about/our-management': typeof AboutOurManagementRoute
  '/about/our-mission': typeof AboutOurMissionRoute
  '/about/our-vision': typeof AboutOurVisionRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/explore/blog': typeof ExploreBlogRoute
  '/explore/careers': typeof ExploreCareersRoute
  '/explore/guards-recruitment': typeof ExploreGuardsRecruitmentRoute
  '/services/access-control': typeof ServicesAccessControlRoute
  '/services/cash-in-transit': typeof ServicesCashInTransitRoute
  '/services/escort-services': typeof ServicesEscortServicesRoute
  '/services/maritime-security': typeof ServicesMaritimeSecurityRoute
  '/services/personal-protection': typeof ServicesPersonalProtectionRoute
  '/services/reception-protocol': typeof ServicesReceptionProtocolRoute
  '/services/security-equipment': typeof ServicesSecurityEquipmentRoute
  '/services/special-investigation': typeof ServicesSpecialInvestigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/guarding-patrol': typeof GuardingPatrolRoute
  '/sectors': typeof SectorsRoute
  '/tech-cctv': typeof TechCctvRoute
  '/about/affiliations': typeof AboutAffiliationsRoute
  '/about/corporate-objectives': typeof AboutCorporateObjectivesRoute
  '/about/our-background': typeof AboutOurBackgroundRoute
  '/about/our-core-values': typeof AboutOurCoreValuesRoute
  '/about/our-management': typeof AboutOurManagementRoute
  '/about/our-mission': typeof AboutOurMissionRoute
  '/about/our-vision': typeof AboutOurVisionRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/explore/blog': typeof ExploreBlogRoute
  '/explore/careers': typeof ExploreCareersRoute
  '/explore/guards-recruitment': typeof ExploreGuardsRecruitmentRoute
  '/services/access-control': typeof ServicesAccessControlRoute
  '/services/cash-in-transit': typeof ServicesCashInTransitRoute
  '/services/escort-services': typeof ServicesEscortServicesRoute
  '/services/maritime-security': typeof ServicesMaritimeSecurityRoute
  '/services/personal-protection': typeof ServicesPersonalProtectionRoute
  '/services/reception-protocol': typeof ServicesReceptionProtocolRoute
  '/services/security-equipment': typeof ServicesSecurityEquipmentRoute
  '/services/special-investigation': typeof ServicesSpecialInvestigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/guarding-patrol': typeof GuardingPatrolRoute
  '/sectors': typeof SectorsRoute
  '/tech-cctv': typeof TechCctvRoute
  '/about/affiliations': typeof AboutAffiliationsRoute
  '/about/corporate-objectives': typeof AboutCorporateObjectivesRoute
  '/about/our-background': typeof AboutOurBackgroundRoute
  '/about/our-core-values': typeof AboutOurCoreValuesRoute
  '/about/our-management': typeof AboutOurManagementRoute
  '/about/our-mission': typeof AboutOurMissionRoute
  '/about/our-vision': typeof AboutOurVisionRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/explore/blog': typeof ExploreBlogRoute
  '/explore/careers': typeof ExploreCareersRoute
  '/explore/guards-recruitment': typeof ExploreGuardsRecruitmentRoute
  '/services/access-control': typeof ServicesAccessControlRoute
  '/services/cash-in-transit': typeof ServicesCashInTransitRoute
  '/services/escort-services': typeof ServicesEscortServicesRoute
  '/services/maritime-security': typeof ServicesMaritimeSecurityRoute
  '/services/personal-protection': typeof ServicesPersonalProtectionRoute
  '/services/reception-protocol': typeof ServicesReceptionProtocolRoute
  '/services/security-equipment': typeof ServicesSecurityEquipmentRoute
  '/services/special-investigation': typeof ServicesSpecialInvestigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/guarding-patrol'
    | '/sectors'
    | '/tech-cctv'
    | '/about/affiliations'
    | '/about/corporate-objectives'
    | '/about/our-background'
    | '/about/our-core-values'
    | '/about/our-management'
    | '/about/our-mission'
    | '/about/our-vision'
    | '/about/testimonials'
    | '/explore/blog'
    | '/explore/careers'
    | '/explore/guards-recruitment'
    | '/services/access-control'
    | '/services/cash-in-transit'
    | '/services/escort-services'
    | '/services/maritime-security'
    | '/services/personal-protection'
    | '/services/reception-protocol'
    | '/services/security-equipment'
    | '/services/special-investigation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/guarding-patrol'
    | '/sectors'
    | '/tech-cctv'
    | '/about/affiliations'
    | '/about/corporate-objectives'
    | '/about/our-background'
    | '/about/our-core-values'
    | '/about/our-management'
    | '/about/our-mission'
    | '/about/our-vision'
    | '/about/testimonials'
    | '/explore/blog'
    | '/explore/careers'
    | '/explore/guards-recruitment'
    | '/services/access-control'
    | '/services/cash-in-transit'
    | '/services/escort-services'
    | '/services/maritime-security'
    | '/services/personal-protection'
    | '/services/reception-protocol'
    | '/services/security-equipment'
    | '/services/special-investigation'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/guarding-patrol'
    | '/sectors'
    | '/tech-cctv'
    | '/about/affiliations'
    | '/about/corporate-objectives'
    | '/about/our-background'
    | '/about/our-core-values'
    | '/about/our-management'
    | '/about/our-mission'
    | '/about/our-vision'
    | '/about/testimonials'
    | '/explore/blog'
    | '/explore/careers'
    | '/explore/guards-recruitment'
    | '/services/access-control'
    | '/services/cash-in-transit'
    | '/services/escort-services'
    | '/services/maritime-security'
    | '/services/personal-protection'
    | '/services/reception-protocol'
    | '/services/security-equipment'
    | '/services/special-investigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  GuardingPatrolRoute: typeof GuardingPatrolRoute
  SectorsRoute: typeof SectorsRoute
  TechCctvRoute: typeof TechCctvRoute
  AboutAffiliationsRoute: typeof AboutAffiliationsRoute
  AboutCorporateObjectivesRoute: typeof AboutCorporateObjectivesRoute
  AboutOurBackgroundRoute: typeof AboutOurBackgroundRoute
  AboutOurCoreValuesRoute: typeof AboutOurCoreValuesRoute
  AboutOurManagementRoute: typeof AboutOurManagementRoute
  AboutOurMissionRoute: typeof AboutOurMissionRoute
  AboutOurVisionRoute: typeof AboutOurVisionRoute
  AboutTestimonialsRoute: typeof AboutTestimonialsRoute
  ExploreBlogRoute: typeof ExploreBlogRoute
  ExploreCareersRoute: typeof ExploreCareersRoute
  ExploreGuardsRecruitmentRoute: typeof ExploreGuardsRecruitmentRoute
  ServicesAccessControlRoute: typeof ServicesAccessControlRoute
  ServicesCashInTransitRoute: typeof ServicesCashInTransitRoute
  ServicesEscortServicesRoute: typeof ServicesEscortServicesRoute
  ServicesMaritimeSecurityRoute: typeof ServicesMaritimeSecurityRoute
  ServicesPersonalProtectionRoute: typeof ServicesPersonalProtectionRoute
  ServicesReceptionProtocolRoute: typeof ServicesReceptionProtocolRoute
  ServicesSecurityEquipmentRoute: typeof ServicesSecurityEquipmentRoute
  ServicesSpecialInvestigationRoute: typeof ServicesSpecialInvestigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarding-patrol': {
      id: '/guarding-patrol'
      path: '/guarding-patrol'
      fullPath: '/guarding-patrol'
      preLoaderRoute: typeof GuardingPatrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-cctv': {
      id: '/tech-cctv'
      path: '/tech-cctv'
      fullPath: '/tech-cctv'
      preLoaderRoute: typeof TechCctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/affiliations': {
      id: '/about/affiliations'
      path: '/about/affiliations'
      fullPath: '/about/affiliations'
      preLoaderRoute: typeof AboutAffiliationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/corporate-objectives': {
      id: '/about/corporate-objectives'
      path: '/about/corporate-objectives'
      fullPath: '/about/corporate-objectives'
      preLoaderRoute: typeof AboutCorporateObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/our-background': {
      id: '/about/our-background'
      path: '/about/our-background'
      fullPath: '/about/our-background'
      preLoaderRoute: typeof AboutOurBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/our-core-values': {
      id: '/about/our-core-values'
      path: '/about/our-core-values'
      fullPath: '/about/our-core-values'
      preLoaderRoute: typeof AboutOurCoreValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/our-management': {
      id: '/about/our-management'
      path: '/about/our-management'
      fullPath: '/about/our-management'
      preLoaderRoute: typeof AboutOurManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/our-mission': {
      id: '/about/our-mission'
      path: '/about/our-mission'
      fullPath: '/about/our-mission'
      preLoaderRoute: typeof AboutOurMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/our-vision': {
      id: '/about/our-vision'
      path: '/about/our-vision'
      fullPath: '/about/our-vision'
      preLoaderRoute: typeof AboutOurVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/testimonials': {
      id: '/about/testimonials'
      path: '/about/testimonials'
      fullPath: '/about/testimonials'
      preLoaderRoute: typeof AboutTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/blog': {
      id: '/explore/blog'
      path: '/explore/blog'
      fullPath: '/explore/blog'
      preLoaderRoute: typeof ExploreBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/careers': {
      id: '/explore/careers'
      path: '/explore/careers'
      fullPath: '/explore/careers'
      preLoaderRoute: typeof ExploreCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/guards-recruitment': {
      id: '/explore/guards-recruitment'
      path: '/explore/guards-recruitment'
      fullPath: '/explore/guards-recruitment'
      preLoaderRoute: typeof ExploreGuardsRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/access-control': {
      id: '/services/access-control'
      path: '/services/access-control'
      fullPath: '/services/access-control'
      preLoaderRoute: typeof ServicesAccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cash-in-transit': {
      id: '/services/cash-in-transit'
      path: '/services/cash-in-transit'
      fullPath: '/services/cash-in-transit'
      preLoaderRoute: typeof ServicesCashInTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/escort-services': {
      id: '/services/escort-services'
      path: '/services/escort-services'
      fullPath: '/services/escort-services'
      preLoaderRoute: typeof ServicesEscortServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maritime-security': {
      id: '/services/maritime-security'
      path: '/services/maritime-security'
      fullPath: '/services/maritime-security'
      preLoaderRoute: typeof ServicesMaritimeSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/personal-protection': {
      id: '/services/personal-protection'
      path: '/services/personal-protection'
      fullPath: '/services/personal-protection'
      preLoaderRoute: typeof ServicesPersonalProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/reception-protocol': {
      id: '/services/reception-protocol'
      path: '/services/reception-protocol'
      fullPath: '/services/reception-protocol'
      preLoaderRoute: typeof ServicesReceptionProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/security-equipment': {
      id: '/services/security-equipment'
      path: '/services/security-equipment'
      fullPath: '/services/security-equipment'
      preLoaderRoute: typeof ServicesSecurityEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/special-investigation': {
      id: '/services/special-investigation'
      path: '/services/special-investigation'
      fullPath: '/services/special-investigation'
      preLoaderRoute: typeof ServicesSpecialInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  GuardingPatrolRoute: GuardingPatrolRoute,
  SectorsRoute: SectorsRoute,
  TechCctvRoute: TechCctvRoute,
  AboutAffiliationsRoute: AboutAffiliationsRoute,
  AboutCorporateObjectivesRoute: AboutCorporateObjectivesRoute,
  AboutOurBackgroundRoute: AboutOurBackgroundRoute,
  AboutOurCoreValuesRoute: AboutOurCoreValuesRoute,
  AboutOurManagementRoute: AboutOurManagementRoute,
  AboutOurMissionRoute: AboutOurMissionRoute,
  AboutOurVisionRoute: AboutOurVisionRoute,
  AboutTestimonialsRoute: AboutTestimonialsRoute,
  ExploreBlogRoute: ExploreBlogRoute,
  ExploreCareersRoute: ExploreCareersRoute,
  ExploreGuardsRecruitmentRoute: ExploreGuardsRecruitmentRoute,
  ServicesAccessControlRoute: ServicesAccessControlRoute,
  ServicesCashInTransitRoute: ServicesCashInTransitRoute,
  ServicesEscortServicesRoute: ServicesEscortServicesRoute,
  ServicesMaritimeSecurityRoute: ServicesMaritimeSecurityRoute,
  ServicesPersonalProtectionRoute: ServicesPersonalProtectionRoute,
  ServicesReceptionProtocolRoute: ServicesReceptionProtocolRoute,
  ServicesSecurityEquipmentRoute: ServicesSecurityEquipmentRoute,
  ServicesSpecialInvestigationRoute: ServicesSpecialInvestigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
